/* ---------------------------------------------------------------------------
   GET /new — What's New, rendered here.

     → KV (stale-while-revalidate, own key)
     → parse the SAME sheet the override reads, filtered on `blog`
     → HTML, with its own security headers

   Three things this route deliberately does NOT do:

     · It does not call the model, and it does not touch /api/ask, its origin
       allow-list, its rate limiter or its gates. What's New is one more read
       of one sheet.
     · It does not read `override:sheet`. That key holds the override's already
       filtered, already grouped result with these columns discarded — reading
       it here would silently show a subset of what Nick picked. This route
       keeps its own key, `blog:sheet`.
     · It ships no JavaScript. The page is built here so that inside the
       portal's frame, on an old phone, it costs one request and no script.

   THE HEADERS ARE SET HERE, IN CODE, AND THAT IS NOT A STYLE CHOICE.
   Cloudflare does not apply `_headers` to responses generated by Pages
   Functions — not the per-page CSP, and not the `/*` block either. Every other
   page on this site gets its policy from that file. This one cannot, so it
   carries its own via securityHeaders(). Leave them out and /new ships with no
   CSP and no frame-ancestors, which fails silently in the worst direction: the
   portal's iframe still works, and so does everybody else's.
   --------------------------------------------------------------------------- */

import curation from '../src/curation.json';
import { DEFAULT_CSV_URL, CACHE_TTL_SECONDS } from '../src/sheet.js';
import { BLOG_KEY, parseWhatsNew, renderPage, securityHeaders } from '../src/blog.js';

const SHEET_TIMEOUT_MS = 8000;
let refreshing = false; // per-isolate guard, so one stale window fetches once

/* Same shape as the override's fetch, deliberately: a login page is HTML and
   would parse into nonsense rows rather than fail, so it is caught by shape
   before it is parsed by content. */
async function fetchBlog(env) {
  const url = env.SHEET_CSV_URL || DEFAULT_CSV_URL;
  const response = await fetch(url, {
    headers: { accept: 'text/csv' },
    signal: AbortSignal.timeout(SHEET_TIMEOUT_MS),
    cf: { cacheTtl: 60 },
  });
  if (!response.ok) throw new Error(`sheet ${response.status}`);

  const text = await response.text();
  if (/^\s*</.test(text)) throw new Error('sheet returned HTML, not CSV');

  const parsed = parseWhatsNew(text);
  return {
    fetchedAt: Date.now(),
    version: parsed.version,
    items: parsed.items,
    notes: parsed.notes,
  };
}

async function refreshBlog(env) {
  if (refreshing) return null;
  refreshing = true;
  try {
    const fresh = await fetchBlog(env);
    await env.GRID.put(BLOG_KEY, JSON.stringify(fresh));
    return fresh;
  } catch (error) {
    console.warn('blog refresh failed, keeping what we have:', error);
    return null;
  } finally {
    refreshing = false;
  }
}

/**
 * A stale copy is served AS IS and the refresh happens after the response.
 * The worst case is a page a few minutes behind the sheet; the case we refuse
 * is a person waiting on docs.google.com before they see anything.
 */
async function getBlog(env, ctx) {
  if (!env.GRID) {
    // No KV binding (local `python3 -m http.server`, a misconfigured preview):
    // fetch once rather than render an empty page that looks like an empty
    // sheet. Slower, honest, and only on that path.
    try {
      return await fetchBlog(env);
    } catch (error) {
      console.warn('blog fetch failed with no KV to fall back on:', error);
      return null;
    }
  }

  let stored = null;
  try {
    stored = await env.GRID.get(BLOG_KEY, 'json');
  } catch (error) {
    console.warn('blog cache unreadable:', error);
  }

  const age = stored ? (Date.now() - stored.fetchedAt) / 1000 : Infinity;
  if (stored && age < CACHE_TTL_SECONDS) return stored;

  if (stored) {
    ctx?.waitUntil?.(refreshBlog(env));
    return stored;
  }
  return refreshBlog(env);
}

export async function onRequestGet(context) {
  const { env } = context;

  const blog = await getBlog(env, context);
  const html = renderPage({ items: blog?.items ?? [], topics: curation.topics });

  return new Response(html, { status: 200, headers: securityHeaders() });
}

/* Anything but GET. A page is a page. */
export function onRequest() {
  return new Response('Method not allowed', {
    status: 405,
    headers: { allow: 'GET', 'content-type': 'text/plain; charset=utf-8' },
  });
}
